
-- 部门
create table dept(
    id bigint,
    name varchar(50),
    the_sort integer,
    descn varchar(200),
    parent_id bigint
);
alter table dept add constraint pk_dept primary key(id);
alter table dept alter column id bigint generated by default as identity(start with 1);
alter table dept add constraint fk_dept_parent foreign key(parent_id) references dept(id);

-- 菜单
create table menu(
    id bigint,
    name varchar(50),
    image varchar(50),
    url varchar(50),
    the_sort integer,
    descn varchar(200),
    parent_id bigint,
    qtip varchar(50)
);
alter table menu add constraint pk_menu primary key(id);
alter table menu alter column id bigint generated by default as identity(start with 1);
alter table menu add constraint fk_menu_parent foreign key(parent_id) references menu(id);

-- 资源
create table resc(
    id bigint,
    name varchar(50),
    res_type varchar(50),
    res_string varchar(200),
    descn varchar(200)
);
alter table resc add constraint pk_resc primary key(id);
alter table resc alter column id bigint generated by default as identity(start with 1);

-- 角色
create table role(
    id bigint,
    name varchar(50),
    descn varchar(200)
);
alter table role add constraint pk_role primary key(id);
alter table role alter column id bigint generated by default as identity(start with 1);

-- 用户
create table user(
    id bigint,
    username varchar(50),
    password varchar(50),
    status integer,
    descn varchar(200),
    dept_id bigint
);
alter table user add constraint pk_user primary key(id);
alter table user alter column id bigint generated by default as identity(start with 1);
alter table user add constraint fk_user_dept foreign key(dept_id) references dept(id);

-- 菜单角色连接表
create table menu_role(
    menu_id bigint,
    role_id bigint
);
alter table menu_role add constraint pk_menu_role primary key(menu_id, role_id);
alter table menu_role add constraint fk_menu_role_menu foreign key(menu_id) references menu(id);
alter table menu_role add constraint fk_menu_role_role foreign key(role_id) references role(id);

-- 资源角色连接表
create table resc_role(
    resc_id bigint,
    role_id bigint
);
alter table resc_role add constraint pk_resc_role primary key(resc_id, role_id);
alter table resc_role add constraint fk_resc_role_resc foreign key(resc_id) references resc(id);
alter table resc_role add constraint fk_resc_role_role foreign key(role_id) references role(id);

-- 用户角色连接表
create table user_role(
    user_id bigint,
    role_id bigint
);
alter table user_role add constraint pk_user_role primary key(user_id, role_id);
alter table user_role add constraint fk_user_role_user foreign key(user_id) references user(id);
alter table user_role add constraint fk_user_role_role foreign key(role_id) references role(id);

-- sid表示ACL中的某一个身份
create table acl_sid(
    id bigint,
    principal integer,
    sid varchar(100)
);
alter table acl_sid add constraint pk_acl_sid primary key(id);
alter table acl_sid alter column id bigint generated by default as identity(start with 1);
alter table acl_sid add constraint uk_acl_sid unique(sid, principal);

-- class表示ACL中的java类
create table acl_class(
    id bigint,
    class varchar(100),
    sid varchar(100)
);
alter table acl_class add constraint pk_acl_class primary key(id);
alter table acl_class alter column id bigint generated by default as identity(start with 1);
alter table acl_class add constraint uk_acl_class unique(class);

-- 保存对象实例的唯一标示
create table acl_object_identity(
    id bigint,
    object_id_class bigint,
    object_id_identity bigint,
    parent_object bigint,
    owner_sid bigint,
    entries_inheriting integer
);
alter table acl_object_identity add constraint pk_acl_object_identity primary key(id);
alter table acl_object_identity alter column id bigint generated by default as identity(start with 1);
alter table acl_object_identity add constraint uk_object_identity unique(object_id_class,object_id_identity);
alter table acl_object_identity add constraint fk_object_identity_parent_object foreign key(parent_object) references acl_object_identity(id);
alter table acl_object_identity add constraint fk_object_identity_object_id foreign key(object_id_class) references acl_class(id);
alter table acl_object_identity add constraint fk_object_identity_owner_sid foreign key(owner_sid) references acl_sid(id);

-- 每个对象实例对应的多个访问权限
create table acl_entry(
    id bigint,
    acl_object_identity bigint,
    ace_order integer,
    sid bigint,
    mask integer,
    granting integer,
    audit_success integer,
    audit_failure integer
);
alter table acl_entry add constraint pk_acl_entry primary key(id);
alter table acl_entry alter column id bigint generated by default as identity(start with 1);
alter table acl_entry add constraint uk_acl_entry unique(acl_object_identity, ace_order);
alter table acl_entry add constraint fk_acl_entry_acl_object_identity foreign key(acl_object_identity) references acl_object_identity(id);
alter table acl_entry add constraint fk_acl_entry_sid foreign key(sid) references acl_sid(id);


--//@UNDO

drop table acl_entry cascade;
drop table acl_object_identity cascade;
drop table acl_class cascade;
drop table acl_sid cascade;

drop table user_role cascade;
drop table resc_role cascade;
drop table menu_role cascade;
drop table user cascade;
drop table role cascade;
drop table resc cascade;
drop table menu cascade;
drop table dept cascade;


