
-- 部门信息表
create table department(
    id bigint, -- 部门编号
    name varchar(20), -- 部门名称
    descn varchar(200) -- 部门描述
);
alter table department add constraint pk_department primary key(id);
alter table department alter column id bigint generated by default as identity(start with 1);

-- 员工状态表
create table state(
    id bigint, -- 状态编号
    name varchar(10), -- 状态名称
    descn varchar(200) -- 状态描述
);
alter table state add constraint pk_state primary key(id);
alter table state alter column id bigint generated by default as identity(start with 1);

-- 工作职位表
create table job(
    id bigint, -- 职位编号
    name varchar(20), -- 职位名称
    descn varchar(200) -- 职位描述
);
alter table job add constraint pk_job primary key(id);
alter table job alter column id bigint generated by default as identity(start with 1);

-- 员工信息表
create table employee(
    id bigint, -- 员工编号
    name varchar(20), -- 姓名
    sex integer, -- 性别
    birthday datetime, -- 出生日期
    learn varchar(10), -- 学历
    post varchar(10), -- 职称
    department_id bigint, -- 外键，部门
    job_id bigint, -- 外键，职位
    tel varchar(20), -- 电话
    addr varchar(200), -- 地址
    state_id bigint -- 外键，状态
);
alter table employee add constraint pk_employee primary key(id);
alter table employee alter column id bigint generated by default as identity(start with 1);
alter table employee add constraint fk_employee_department foreign key(department_id) references department(id);
alter table employee add constraint fk_employee_job foreign key(job_id) references job(id);
alter table employee add constraint fk_employee_state foreign key(state_id) references state(id);

-- 公告信息表
create table affice(
    id bigint, -- 公告编号
    title varchar(40), -- 公告标题
    time datetime, -- 公告发布时间
    employee_id bigint, -- 外键，发布公告员工
    content varchar(2000) -- 公告内容
);
alter table affice add constraint pk_affice primary key(id);
alter table affice alter column id bigint generated by default as identity(start with 1);
alter table affice add constraint fk_affice_employee foreign key(employee_id) references employee(id);

-- 公文信息表
create table bumf(
    id bigint, -- 公文编号
    sender bigint, -- 外键，发送者
    accepter bigint, -- 外键，接受者编号
    title varchar(40), -- 题目
    time datetime, -- 时间
    content varchar(2000), -- 内容
    affix varchar(40), -- 附件名称
    examine integer, -- 处理结果
    sign integer -- 标志
);
alter table bumf add constraint pk_bumf primary key(id);
alter table bumf alter column id bigint generated by default as identity(start with 1);
alter table bumf add constraint fk_bumf_sender foreign key(sender) references employee(id);
alter table bumf add constraint fk_bumf_accepter foreign key(accepter) references employee(id);

-- 短信息表
create table message(
    id bigint, -- 短信息编号
    title varchar(40), -- 题目
    time datetime, -- 时间
    sender bigint, -- 外键，发送者
    accepter bigint, -- 外键，接受者
    content varchar(2000), -- 内容
    status integer -- 标示短信是否被查看
);
alter table message add constraint pk_message primary key(id);
alter table message alter column id bigint generated by default as identity(start with 1);
alter table message add constraint fk_message_sender foreign key(sender) references employee(id);
alter table message add constraint fk_message_accepter foreign key(accepter) references employee(id);

-- 上下班描述表
create table sign_state(
    id bigint, -- 上下班编号
    name varchar(20), -- 上下班名称
    time datetime -- 系统时间
);
alter table sign_state add constraint pk_sign_state primary key(id);
alter table sign_state alter column id bigint generated by default as identity(start with 1);

-- 员工上下班描述表
create table sign(
    id bigint, -- 员工上下班编号
    time datetime, -- 系统时间
    employee_id bigint, -- 员工编号
    late integer, -- 是否迟到
    quit integer, -- 是否下班
    leave integer, -- 是否早退
    work integer, -- 工作状态
    sign_state_id bigint -- 外键，上下班描述
);
alter table sign add constraint pk_sign primary key(id);
alter table sign alter column id bigint generated by default as identity(start with 1);
alter table sign add constraint fk_sign_employee foreign key(employee_id) references employee(id);
alter table sign add constraint fk_sign_sign_state foreign key(sign_state_id) references sign_state(id);

--//@UNDO

drop table sign cascade;
drop table sign_state cascade;
drop table message cascade;
drop table bumf cascade;
drop table affice cascade;
drop table employee cascade;
drop table job cascade;
drop table state cascade;
drop table department cascade;
