package com.family168.leona.domain;


// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Affice .
 *
 * @author Lingo
 */
@Entity
@Table(name = "AFFICE")
public class Affice implements java.io.Serializable {
    /** null. */
    private Long id;

    /** null. */
    private Employee employee;

    /** null. */
    private String title;

    /** null. */
    private Date time;

    /** null. */
    private String content;

    public Affice() {
    }

    public Affice(Employee employee, String title, Date time,
        String content) {
        this.employee = employee;
        this.title = title;
        this.time = time;
        this.content = content;
    }

    /** @return null. */
    @Id
    @GeneratedValue
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /** @param id null. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMPLOYEE_ID")
    public Employee getEmployee() {
        return this.employee;
    }

    /** @param employee null. */
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    /** @return null. */
    @Column(name = "TITLE", length = 40)
    public String getTitle() {
        return this.title;
    }

    /** @param title null. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** @return null. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "TIME", length = 6)
    public Date getTime() {
        return this.time;
    }

    /** @param time null. */
    public void setTime(Date time) {
        this.time = time;
    }

    /** @return null. */
    @Column(name = "CONTENT", length = 2000)
    public String getContent() {
        return this.content;
    }

    /** @param content null. */
    public void setContent(String content) {
        this.content = content;
    }
}
