package com.family168.leona.domain;


// Generated by Hibernate Tools
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Department .
 *
 * @author Lingo
 */
@Entity
@Table(name = "DEPARTMENT")
public class Department implements java.io.Serializable {
    /** null. */
    private Long id;

    /** null. */
    private String name;

    /** null. */
    private String descn;

    /** . */
    private Set<Employee> employees = new HashSet<Employee>(0);

    public Department() {
    }

    public Department(String name, String descn, Set<Employee> employees) {
        this.name = name;
        this.descn = descn;
        this.employees = employees;
    }

    /** @return null. */
    @Id
    @GeneratedValue
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /** @param id null. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "NAME", length = 20)
    public String getName() {
        return this.name;
    }

    /** @param name null. */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    @Column(name = "DESCN", length = 200)
    public String getDescn() {
        return this.descn;
    }

    /** @param descn null. */
    public void setDescn(String descn) {
        this.descn = descn;
    }

    /** @return . */
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "department")
    public Set<Employee> getEmployees() {
        return this.employees;
    }

    /** @param employees . */
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }
}
