package com.family168.leona.domain;


// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Message .
 *
 * @author Lingo
 */
@Entity
@Table(name = "MESSAGE")
public class Message implements java.io.Serializable {
    /** null. */
    private Long id;

    /** null. */
    private Employee accepter;

    /** null. */
    private Employee sender;

    /** null. */
    private String title;

    /** null. */
    private Date time;

    /** null. */
    private String content;

    /** null. */
    private Integer status;

    public Message() {
    }

    public Message(Employee accepter, Employee sender, String title,
        Date time, String content, Integer status) {
        this.accepter = accepter;
        this.sender = sender;
        this.title = title;
        this.time = time;
        this.content = content;
        this.status = status;
    }

    /** @return null. */
    @Id
    @GeneratedValue
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /** @param id null. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACCEPTER")
    public Employee getAccepter() {
        return this.accepter;
    }

    /** @param accepter null. */
    public void setAccepter(Employee accepter) {
        this.accepter = accepter;
    }

    /** @return null. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SENDER")
    public Employee getSender() {
        return this.sender;
    }

    /** @param sender null. */
    public void setSender(Employee sender) {
        this.sender = sender;
    }

    /** @return null. */
    @Column(name = "TITLE", length = 40)
    public String getTitle() {
        return this.title;
    }

    /** @param title null. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** @return null. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "TIME", length = 6)
    public Date getTime() {
        return this.time;
    }

    /** @param time null. */
    public void setTime(Date time) {
        this.time = time;
    }

    /** @return null. */
    @Column(name = "CONTENT", length = 2000)
    public String getContent() {
        return this.content;
    }

    /** @param content null. */
    public void setContent(String content) {
        this.content = content;
    }

    /** @return null. */
    @Column(name = "STATUS")
    public Integer getStatus() {
        return this.status;
    }

    /** @param status null. */
    public void setStatus(Integer status) {
        this.status = status;
    }
}
