package com.family168.dsl

import com.family168.Order
import java.lang.Double
import java.math.BigDecimal

expander orderPricing.dsl

rule " order 0.9 discount"
    when
        order price larger than 100
    then
        do 0.9 discount
        #加入 > 就可以在drl/dsl 中直接写入drl 语法
        >System.out.println("original price:" + order.getOriginalPrice() + " discount price:" + order.getTotalPrice());
end

