

CREATE TABLE DBDEPLOY_DEMO.ADDRESS (
ADDRESS_ID INTEGER
,ADDRESS_LINE_1 VARCHAR(50)
,ADDRESS_LINE_2 VARCHAR(50)
,ADDRESS_LINE_3 VARCHAR(50)
,ADDRESS_LINE_4 VARCHAR(50)
,ADDRESS_LINE_5 VARCHAR(50)
,ZIP VARCHAR(100)
,VALID_FROM DATE
,VALID_UNTIL DATE
);

ALTER TABLE DBDEPLOY_DEMO.ADDRESS ADD CONSTRAINT PK_ADDRESS PRIMARY KEY (ADDRESS_ID);

ALTER TABLE DBDEPLOY_DEMO.CUSTOMER ADD COLUMN ADDRESS_ID INTEGER;

ALTER TABLE DBDEPLOY_DEMO.CUSTOMER ADD CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES DBDEPLOY_DEMO.ADDRESS(ADDRESS_ID);

--//@UNDO

CREATE TABLE DBDEPLOY_DEMO.CUSTOMER_NEW (
CUSTOMER_ID INTEGER
,FIRST_NAME VARCHAR(50)
,MIDDLE_NAMES VARCHAR(100)
,LAST_NAME VARCHAR(50)
,DOB DATE
);

INSERT INTO DBDEPLOY_DEMO.CUSTOMER_NEW (
CUSTOMER_ID
,FIRST_NAME
,MIDDLE_NAMES
,LAST_NAME
,DOB
)
SELECT
CUSTOMER_ID
,FIRST_NAME
,MIDDLE_NAMES
,LAST_NAME
,DOB
FROM DBDEPLOY_DEMO.CUSTOMER;

DROP TABLE DBDEPLOY_DEMO.CUSTOMER IF EXISTS;

ALTER TABLE DBDEPLOY_DEMO.CUSTOMER_NEW RENAME TO DBDEPLOY_DEMO.CUSTOMER;

DROP TABLE DBDEPLOY_DEMO.ADDRESS IF EXISTS;
