INSERT INTO DBDEPLOY_DEMO.ADDRESS (
ADDRESS_ID
,ADDRESS_LINE_1
,ADDRESS_LINE_2
,ADDRESS_LINE_3
,ADDRESS_LINE_4
,ADDRESS_LINE_5
,ZIP
,VALID_FROM
,VALID_UNTIL)
VALUES (
1
,'4 Allwrights Cottages'
,'Horsepond Road'
,'Gallowstree Common'
,'Oxfordshire'
,'UK'
,'RG4 9DA'
,'1995-01-01'
,NULL
);

UPDATE DBDEPLOY_DEMO.CUSTOMER SET
ADDRESS_ID = 1
WHERE CUSTOMER_ID = 1;

--//@UNDO


UPDATE DBDEPLOY_DEMO.CUSTOMER SET
ADDRESS_ID = NULL
WHERE CUSTOMER_ID = 1;


DELETE FROM DBDEPLOY_DEMO.ADDRESS;
